// Auto-generated by scripts/sync-sheet.ts — DO NOT EDIT BY HAND.
// Source: Google Sheet "selle-jallot-database.xlsx"
// Last sync: 2026-04-28T08:11:19.862Z
// 169 brands · 438 models · 5 blanket-incompatible brands

export type CompatibilityStatus = "compatible" | "check" | "incompatible";

export interface BikeModel {
  diameter: number;
  type: string;
  status: CompatibilityStatus;
  note?: string;
}

export interface CompatibleBrand {
  name: string;
  flag: "attention_modele" | null;
  models: Record<string, BikeModel>;
}

export interface IncompatibleBrand {
  name: string;
  reason: string;
  scope: "all" | string[];
}

export interface BikesDatabase {
  meta: {
    updated: string;
    diametersSupported: number[];
    types: string[];
    counts: { brands: number; models: number; incompatibleBrands: number };
  };
  brands: CompatibleBrand[];
  incompatibleBrands: IncompatibleBrand[];
}

export const database: BikesDatabase = {
  "meta": {
    "updated": "2026-04-28",
    "diametersSupported": [
      27.2,
      30.9,
      31.6,
      34
    ],
    "types": [
      "Cargo",
      "Cargo E",
      "Enfant",
      "Enfant E",
      "Fitness",
      "Pliant",
      "Tricycle E",
      "VTC",
      "VTC E",
      "VTT",
      "VTT E",
      "VTTAE",
      "Ville",
      "Ville E",
      "Vintage"
    ],
    "counts": {
      "brands": 169,
      "models": 438,
      "incompatibleBrands": 5
    }
  },
  "brands": [
    {
      "name": "ABIMOTA",
      "flag": null,
      "models": {
        "Modèle standard": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "AddBike",
      "flag": null,
      "models": {
        "Front": {
          "diameter": 27.2,
          "type": "Cargo",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Airdrop Bikes",
      "flag": null,
      "models": {
        "Edit": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Filter": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Ampler",
      "flag": null,
      "models": {
        "Cruse": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Curt": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Stout": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Ancillotti",
      "flag": null,
      "models": {
        "Epyon": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Angell Mobility",
      "flag": null,
      "models": {
        "Angell Bike": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Arcade Cycles",
      "flag": null,
      "models": {
        "First": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Shade": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Atherton Bikes",
      "flag": null,
      "models": {
        "AM.150": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "DW.170": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "AURUM",
      "flag": null,
      "models": {
        "Hummer": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Magma": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Author Bikes",
      "flag": null,
      "models": {
        "Instinct": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Axxome",
      "flag": null,
      "models": {
        "V1": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Azor",
      "flag": null,
      "models": {
        "Oma": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        },
        "Opafiets E": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Babboe",
      "flag": null,
      "models": {
        "Big": {
          "diameter": 27.2,
          "type": "Cargo",
          "status": "compatible"
        },
        "City": {
          "diameter": 27.2,
          "type": "Cargo",
          "status": "compatible"
        },
        "City-E": {
          "diameter": 27.2,
          "type": "Cargo E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Bakfiets.nl",
      "flag": null,
      "models": {
        "Cargobike Long": {
          "diameter": 27.2,
          "type": "Cargo",
          "status": "compatible"
        },
        "Cargobike Short E": {
          "diameter": 27.2,
          "type": "Cargo E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Batavus",
      "flag": null,
      "models": {
        "Bryte": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        },
        "Dinsdag E-go": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Finez E-go": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "BeEQ",
      "flag": null,
      "models": {
        "S1": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Bergamont",
      "flag": null,
      "models": {
        "E-Horizon": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "E-Revox": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Revox": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "BH Bikes",
      "flag": null,
      "models": {
        "Lynx Race": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Xtep": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Bike Ahead",
      "flag": null,
      "models": {
        "Biturbo FS": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Bikkel Bikes",
      "flag": null,
      "models": {
        "Ibee": {
          "diameter": 27.2,
          "type": "Cargo E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Bird Bikes",
      "flag": null,
      "models": {
        "Aeris AM1": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Zero AM1": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "BMC",
      "flag": null,
      "models": {
        "Alpenchallenge": {
          "diameter": 27.2,
          "type": "Fitness",
          "status": "compatible"
        },
        "Speedfox": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Twostroke": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "BSP",
      "flag": null,
      "models": {
        "Urban Ride": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Bulls",
      "flag": null,
      "models": {
        "Copperhead EVO AM": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Cross Street": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "Lacuba EVO": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Sonic EVO AM": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Cannondale",
      "flag": null,
      "models": {
        "Habit": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Jekyll": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Quick": {
          "diameter": 27.2,
          "type": "Fitness",
          "status": "compatible"
        },
        "Scalpel": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Trail": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Canyon",
      "flag": null,
      "models": {
        "Commuter": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        },
        "Exceed": {
          "diameter": 27.2,
          "type": "VTT",
          "status": "compatible"
        },
        "Neuron": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Roadlite": {
          "diameter": 27.2,
          "type": "Fitness",
          "status": "compatible"
        },
        "Sender": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Spectral": {
          "diameter": 34.9,
          "type": "VTT",
          "status": "compatible",
          "note": "2024+ frame. Older Spectral CF (2022): 30.9mm."
        },
        "Spectral (2022)": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Torque": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Carqon",
      "flag": null,
      "models": {
        "Cruiser": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Platoo": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Coboc",
      "flag": null,
      "models": {
        "One": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Trekking": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Commencal",
      "flag": null,
      "models": {
        "Meta HT": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Meta Power": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Meta TR": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Supreme DH": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Corratec",
      "flag": null,
      "models": {
        "X-Vert": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Cortina",
      "flag": null,
      "models": {
        "E-Common": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Mozzo": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        },
        "U4 Transport": {
          "diameter": 27.2,
          "type": "Cargo",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Cotic",
      "flag": null,
      "models": {
        "BFe Max": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Rocket": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Cowboy",
      "flag": null,
      "models": {
        "Cowboy 4": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Cowboy 4 ST": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Cowboy Cruiser": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Creme Cycles",
      "flag": null,
      "models": {
        "Doppio": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "compatible"
        },
        "Echo Solo": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Crivit (Lidl)",
      "flag": "attention_modele",
      "models": {
        "Cross Bike (non électrique)": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "check",
          "note": "Les modèles e-bike Crivit ont la batterie dans la tige de selle (incompatibles). Seuls les modèles non-électriques sont compatibles."
        },
        "Mountain Bike (non électrique)": {
          "diameter": 27.2,
          "type": "VTT",
          "status": "check",
          "note": "Les modèles e-bike Crivit ont la batterie dans la tige de selle (incompatibles). Seuls les modèles non-électriques sont compatibles."
        }
      }
    },
    {
      "name": "Crossworx",
      "flag": null,
      "models": {
        "Rage": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Cube",
      "flag": null,
      "models": {
        "Acid": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Kathmandu Hybrid": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "Reaction": {
          "diameter": 27.2,
          "type": "VTT",
          "status": "compatible"
        },
        "Stereo 120": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Stereo 140": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Stereo 150": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Stereo Hybrid": {
          "diameter": 31.6,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Touring Hybrid": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "Town Hybrid": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Cykl",
      "flag": null,
      "models": {
        "Modèle standard": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Decathlon / B'Twin",
      "flag": "attention_modele",
      "models": {
        "Elops 500": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "check",
          "note": "Certains modèles Decathlon utilisent des diamètres non-standards. Vérifiez bien votre modèle."
        },
        "Elops 500 E": {
          "diameter": 31.2,
          "type": "Ville E",
          "status": "incompatible",
          "note": "Diamètre 31.2mm non couvert par Selle Jallot."
        },
        "Elops 900 E": {
          "diameter": 28.6,
          "type": "Ville E",
          "status": "check",
          "note": "Certains modèles Decathlon utilisent des diamètres non-standards. Vérifiez bien votre modèle."
        },
        "Elops R500 (cargo)": {
          "diameter": 34,
          "type": "Cargo",
          "status": "check",
          "note": "Certains modèles Decathlon utilisent des diamètres non-standards. Vérifiez bien votre modèle."
        },
        "Riverside 500": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "check",
          "note": "Certains modèles Decathlon utilisent des diamètres non-standards. Vérifiez bien votre modèle."
        },
        "Riverside 500 E": {
          "diameter": 28.6,
          "type": "VTC E",
          "status": "check",
          "note": "Certains modèles Decathlon utilisent des diamètres non-standards. Vérifiez bien votre modèle."
        },
        "Riverside 520 E": {
          "diameter": 28.6,
          "type": "VTC E",
          "status": "check",
          "note": "Certains modèles Decathlon utilisent des diamètres non-standards. Vérifiez bien votre modèle."
        },
        "Riverside 900": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "check",
          "note": "Certains modèles Decathlon utilisent des diamètres non-standards. Vérifiez bien votre modèle."
        },
        "Riverside 920": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "check",
          "note": "Certains modèles Decathlon utilisent des diamètres non-standards. Vérifiez bien votre modèle."
        },
        "Riverside 920 E": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "check",
          "note": "Certains modèles Decathlon utilisent des diamètres non-standards. Vérifiez bien votre modèle."
        },
        "Rockrider AM 500S": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "check",
          "note": "Certains modèles Decathlon utilisent des diamètres non-standards. Vérifiez bien votre modèle."
        },
        "Rockrider E-ST 500": {
          "diameter": 31.6,
          "type": "VTTAE",
          "status": "check",
          "note": "Certains modèles Decathlon utilisent des diamètres non-standards. Vérifiez bien votre modèle."
        },
        "Rockrider ST100": {
          "diameter": 29.8,
          "type": "VTT",
          "status": "incompatible",
          "note": "Diamètre 29.8mm non couvert par Selle Jallot."
        },
        "Rockrider ST530": {
          "diameter": 31.4,
          "type": "VTT",
          "status": "incompatible",
          "note": "Diamètre 31.4mm non couvert par Selle Jallot."
        },
        "Rockrider Stilus E-AM": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "check",
          "note": "Certains modèles Decathlon utilisent des diamètres non-standards. Vérifiez bien votre modèle."
        },
        "Rockrider XC500": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "check",
          "note": "Certains modèles Decathlon utilisent des diamètres non-standards. Vérifiez bien votre modèle."
        },
        "Rockrider XC900": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "check",
          "note": "Certains modèles Decathlon utilisent des diamètres non-standards. Vérifiez bien votre modèle."
        }
      }
    },
    {
      "name": "Devinci",
      "flag": null,
      "models": {
        "Django": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Troy": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Wilson": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Diamant Bikes",
      "flag": null,
      "models": {
        "Elan": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "Ubari": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Douze Cycles",
      "flag": null,
      "models": {
        "G4": {
          "diameter": 34,
          "type": "Cargo E",
          "status": "compatible"
        },
        "G4i": {
          "diameter": 34,
          "type": "Cargo E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Economie Bikes",
      "flag": null,
      "models": {
        "Modèle standard": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Elops",
      "flag": "attention_modele",
      "models": {
        "Elops 500": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "check",
          "note": "Certains Elops e-bike utilisent des diamètres non-standards (31.2mm). Vérifiez votre modèle."
        },
        "Elops 500 E": {
          "diameter": 31.2,
          "type": "Ville E",
          "status": "incompatible",
          "note": "Diamètre 31.2mm non couvert par Selle Jallot."
        },
        "Elops 900 E": {
          "diameter": 28.6,
          "type": "Ville E",
          "status": "check",
          "note": "Certains Elops e-bike utilisent des diamètres non-standards (31.2mm). Vérifiez votre modèle."
        },
        "Elops R500 (cargo)": {
          "diameter": 34,
          "type": "Cargo",
          "status": "check",
          "note": "Certains Elops e-bike utilisent des diamètres non-standards (31.2mm). Vérifiez votre modèle."
        }
      }
    },
    {
      "name": "Elwing",
      "flag": null,
      "models": {
        "Noma S": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Yuvy": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Engwe",
      "flag": "attention_modele",
      "models": {
        "C20": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "check",
          "note": "Certains modèles Engwe utilisent des tiges de selle non-standards. Vérifier le modèle exact."
        },
        "Engine Pro 2": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "check",
          "note": "Certains modèles Engwe utilisent des tiges de selle non-standards. Vérifier le modèle exact."
        }
      }
    },
    {
      "name": "Esmaltina",
      "flag": null,
      "models": {
        "Modèle standard": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Excelsior Bikes",
      "flag": null,
      "models": {
        "Cita": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Fantic",
      "flag": null,
      "models": {
        "Issimo": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "XF1 Integra": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Fiido",
      "flag": null,
      "models": {
        "D11": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "M1 Pro": {
          "diameter": 27.2,
          "type": "VTT E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Flyer Bikes",
      "flag": null,
      "models": {
        "C8": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "T8": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "Uproc6": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Focus",
      "flag": null,
      "models": {
        "SAM2": {
          "diameter": 34.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Gazelle",
      "flag": null,
      "models": {
        "Chamonix": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Medeo T9": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "Paris": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        },
        "Ultimate C380+": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Ghost Bikes",
      "flag": null,
      "models": {
        "Hybride Square": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "compatible"
        },
        "Lector FS": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Riot": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Giant",
      "flag": null,
      "models": {
        "Anthem Advanced": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Escape": {
          "diameter": 27.2,
          "type": "Fitness",
          "status": "compatible"
        },
        "Explore E+": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "FastRoad": {
          "diameter": 27.2,
          "type": "Fitness",
          "status": "compatible"
        },
        "Fathom": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Reign Advanced": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Talon": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Trance E+": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Trance X": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Gitane",
      "flag": null,
      "models": {
        "e-Gitane": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Granville Bikes",
      "flag": null,
      "models": {
        "E+2": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "GT",
      "flag": null,
      "models": {
        "Force Carbon": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Sensor Carbon": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Zaskar Carbon": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Gudereit",
      "flag": null,
      "models": {
        "ET-8": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "LC-60": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Haibike",
      "flag": null,
      "models": {
        "SDURO HardSeven": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Trekking": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "XDURO AllMtn": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        },
        "XDURO AllTrail": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Helkama",
      "flag": null,
      "models": {
        "Jopo": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        },
        "Solki E": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Ibis",
      "flag": null,
      "models": {
        "Exie": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "HD6": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Ripley": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Ripmo": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Ibis Cycle",
      "flag": null,
      "models": {
        "Ripley": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Ripmo": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "IDworx",
      "flag": null,
      "models": {
        "Flatlander": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Intense",
      "flag": null,
      "models": {
        "Carbine": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Primer": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Tracer": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Italvet",
      "flag": null,
      "models": {
        "Modèle standard": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Kalkhoff",
      "flag": null,
      "models": {
        "Berleen": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Endeavour 7": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "Image": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Koga",
      "flag": null,
      "models": {
        "E-Nova": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Pace": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Kona",
      "flag": null,
      "models": {
        "Big Honzo": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Hei Hei": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Process": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Kronan",
      "flag": null,
      "models": {
        "Classic": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        },
        "Electric": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Kross",
      "flag": null,
      "models": {
        "Level": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "compatible"
        },
        "Soil": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "KTM",
      "flag": null,
      "models": {
        "Macina Gran": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "Macina Kapoho": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Lapierre",
      "flag": null,
      "models": {
        "E-Explorer": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "Overvolt": {
          "diameter": 31.6,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Spicy": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Zesty": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Laroo",
      "flag": null,
      "models": {
        "Cargo": {
          "diameter": 27.2,
          "type": "Cargo E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Last Bikes",
      "flag": null,
      "models": {
        "Kage": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Lejeune",
      "flag": null,
      "models": {
        "Modèle ville (moderne)": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Lemmo",
      "flag": null,
      "models": {
        "One": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Lovens",
      "flag": null,
      "models": {
        "Cargo": {
          "diameter": 27.2,
          "type": "Cargo E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Marin Bikes",
      "flag": null,
      "models": {
        "Alpine Trail": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Rift Zone": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "MBK",
      "flag": null,
      "models": {
        "Crosscountry": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "compatible"
        }
      }
    },
    {
      "name": "MDE Bikes",
      "flag": null,
      "models": {
        "Fourmi": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Fourmi E-Bike": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Megamo",
      "flag": null,
      "models": {
        "Crave": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Raise": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Merida",
      "flag": null,
      "models": {
        "Big.Nine": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Crossway": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "compatible"
        },
        "One-Forty": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "One-Twenty": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "eOne-Sixty": {
          "diameter": 34.9,
          "type": "VTTAE",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Mondraker",
      "flag": null,
      "models": {
        "Crafty": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Dune": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Foxy": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Superfoxy": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Motobécane",
      "flag": "attention_modele",
      "models": {
        "Champion (vintage)": {
          "diameter": 26.6,
          "type": "Vintage",
          "status": "check",
          "note": "Les modèles vintage Motobécane (avant 2000) utilisent souvent des diamètres non-standards (25.4mm ou 26.6mm). Vérifiez votre modèle."
        },
        "Nomade E (récent)": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "check",
          "note": "Les modèles vintage Motobécane (avant 2000) utilisent souvent des diamètres non-standards (25.4mm ou 26.6mm). Vérifiez votre modèle."
        },
        "Sprint 10 (vintage)": {
          "diameter": 25.4,
          "type": "Vintage",
          "status": "check",
          "note": "Les modèles vintage Motobécane (avant 2000) utilisent souvent des diamètres non-standards (25.4mm ou 26.6mm). Vérifiez votre modèle."
        }
      }
    },
    {
      "name": "Moustache",
      "flag": null,
      "models": {
        "Game 27": {
          "diameter": 31.6,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Lundi 27": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Samedi 27 Off": {
          "diameter": 31.6,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Samedi 27 Off 7": {
          "diameter": 31.6,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Samedi 27 Wide 2": {
          "diameter": 31.6,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Samedi 27 Wide 3": {
          "diameter": 31.6,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Samedi 28.7": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "Samedi 29 Off 7": {
          "diameter": 31.6,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Vendredi 28": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Moustache Bikes",
      "flag": null,
      "models": {
        "Voir marque Moustache": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Nakamura",
      "flag": null,
      "models": {
        "Cross 3": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "compatible"
        },
        "Cross 5": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "compatible"
        },
        "E-Cross": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "Power 29": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Neomouv",
      "flag": null,
      "models": {
        "Aniou": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Cyclom": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Lacerta": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Nicolai",
      "flag": null,
      "models": {
        "G1": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Geometron": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Norco",
      "flag": null,
      "models": {
        "Optic": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Range": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Sight": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "NOX Cycles",
      "flag": null,
      "models": {
        "Tevis": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "NS Bikes",
      "flag": null,
      "models": {
        "Define": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Snabb": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Nukeproof",
      "flag": null,
      "models": {
        "Giga 290": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Mega 275": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Mega 290": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Scout 290": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "O2feel",
      "flag": "attention_modele",
      "models": {
        "Equo Cargo": {
          "diameter": 27.2,
          "type": "Cargo E",
          "status": "check",
          "note": "Attention : les modèles iVog, iPeps et iPop ont la batterie intégrée dans le tube de selle et sont INCOMPATIBLES. Les modèles iSwan et iRide sont compatibles."
        },
        "iPeps": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "incompatible",
          "note": "Batterie iPowerFit intégrée dans le tube de selle — tige de selle non remplaçable."
        },
        "iPop": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "incompatible",
          "note": "Batterie iPowerFit intégrée dans le tube de selle — tige de selle non remplaçable."
        },
        "iRide (VTTAE)": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "check",
          "note": "Attention : les modèles iVog, iPeps et iPop ont la batterie intégrée dans le tube de selle et sont INCOMPATIBLES. Les modèles iSwan et iRide sont compatibles."
        },
        "iSwan 6": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "check",
          "note": "Attention : les modèles iVog, iPeps et iPop ont la batterie intégrée dans le tube de selle et sont INCOMPATIBLES. Les modèles iSwan et iRide sont compatibles."
        },
        "iSwan 7": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "check",
          "note": "Attention : les modèles iVog, iPeps et iPop ont la batterie intégrée dans le tube de selle et sont INCOMPATIBLES. Les modèles iSwan et iRide sont compatibles."
        },
        "iSwan City Boost": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "check",
          "note": "Attention : les modèles iVog, iPeps et iPop ont la batterie intégrée dans le tube de selle et sont INCOMPATIBLES. Les modèles iSwan et iRide sont compatibles."
        },
        "iSwan Urban Boost": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "check",
          "note": "Attention : les modèles iVog, iPeps et iPop ont la batterie intégrée dans le tube de selle et sont INCOMPATIBLES. Les modèles iSwan et iRide sont compatibles."
        },
        "iVog 4": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "incompatible",
          "note": "Batterie iPowerFit intégrée dans le tube de selle — tige de selle non remplaçable."
        },
        "iVog 5": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "incompatible",
          "note": "Batterie iPowerFit intégrée dans le tube de selle — tige de selle non remplaçable."
        },
        "iVog Sport": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "check",
          "note": "Attention : les modèles iVog, iPeps et iPop ont la batterie intégrée dans le tube de selle et sont INCOMPATIBLES. Les modèles iSwan et iRide sont compatibles."
        }
      }
    },
    {
      "name": "Octane One",
      "flag": null,
      "models": {
        "Prone": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Void": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Oklö",
      "flag": null,
      "models": {
        "Step-through": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Orange Bikes",
      "flag": null,
      "models": {
        "Five": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Stage": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Switch": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Orbea",
      "flag": null,
      "models": {
        "Katu-E": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Laufey": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Occam": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Rallon": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Wild FS": {
          "diameter": 31.6,
          "type": "VTTAE",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Orbita",
      "flag": null,
      "models": {
        "Modèle standard": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Panda Cargo Bikes",
      "flag": null,
      "models": {
        "Panda": {
          "diameter": 27.2,
          "type": "Cargo E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Pashley",
      "flag": null,
      "models": {
        "Clubman": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        },
        "Roadster": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Pegasus",
      "flag": null,
      "models": {
        "Piazza": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        },
        "Solero E8": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Pelago",
      "flag": null,
      "models": {
        "Bristol": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        },
        "Stavanger": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Peugeot Cycles",
      "flag": null,
      "models": {
        "eT01": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "eU01": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Phatfour",
      "flag": null,
      "models": {
        "FLB": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Pivot",
      "flag": null,
      "models": {
        "Firebird": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Mach 4 SL": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Switchblade": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Trail 429": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Privateer Bikes",
      "flag": null,
      "models": {
        "141": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "161": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Production Privée",
      "flag": null,
      "models": {
        "Shan": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Shan FS": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Propain",
      "flag": null,
      "models": {
        "Hugene": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Spindrift": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Tyee": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Puky",
      "flag": null,
      "models": {
        "Modèle standard": {
          "diameter": 27.2,
          "type": "Enfant",
          "status": "compatible"
        }
      }
    },
    {
      "name": "RAAW MTB",
      "flag": null,
      "models": {
        "Jibb": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Madonna V2": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Radon",
      "flag": null,
      "models": {
        "Jealous": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Swoop": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Raleigh",
      "flag": null,
      "models": {
        "Array": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Mustang": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Raymon",
      "flag": null,
      "models": {
        "CrossRay": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "TarrRay": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        },
        "UrbanRay": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Reine Bike",
      "flag": null,
      "models": {
        "Modèle standard": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Ridgeback",
      "flag": null,
      "models": {
        "Journey": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "compatible"
        },
        "Speed": {
          "diameter": 27.2,
          "type": "Fitness",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Riese & Müller",
      "flag": null,
      "models": {
        "Charger4": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "Delite": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Homage": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Load": {
          "diameter": 34,
          "type": "Cargo E",
          "status": "compatible"
        },
        "Nevo": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Supercharger3": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Riese and Muller",
      "flag": null,
      "models": {
        "Voir Riese & Müller": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Riverside",
      "flag": null,
      "models": {
        "Riverside 500": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "compatible"
        },
        "Riverside 500 E": {
          "diameter": 28.6,
          "type": "VTC E",
          "status": "compatible"
        },
        "Riverside 900": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "compatible"
        },
        "Riverside 920": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Rockrider",
      "flag": "attention_modele",
      "models": {
        "AM 500S": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "check",
          "note": "Certains Rockrider utilisent des diamètres non-standards (29.8mm, 31.4mm). Vérifiez votre modèle exact."
        },
        "E-ST 500": {
          "diameter": 31.6,
          "type": "VTTAE",
          "status": "check",
          "note": "Certains Rockrider utilisent des diamètres non-standards (29.8mm, 31.4mm). Vérifiez votre modèle exact."
        },
        "ST100": {
          "diameter": 29.8,
          "type": "VTT",
          "status": "incompatible",
          "note": "Diamètre 29.8mm non couvert par Selle Jallot."
        },
        "ST530": {
          "diameter": 31.4,
          "type": "VTT",
          "status": "incompatible",
          "note": "Diamètre 31.4mm non couvert par Selle Jallot."
        },
        "Stilus E-AM": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "check",
          "note": "Certains Rockrider utilisent des diamètres non-standards (29.8mm, 31.4mm). Vérifiez votre modèle exact."
        },
        "XC500": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "check",
          "note": "Certains Rockrider utilisent des diamètres non-standards (29.8mm, 31.4mm). Vérifiez votre modèle exact."
        },
        "XC900": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "check",
          "note": "Certains Rockrider utilisent des diamètres non-standards (29.8mm, 31.4mm). Vérifiez votre modèle exact."
        }
      }
    },
    {
      "name": "Rocky Mountain",
      "flag": null,
      "models": {
        "Altitude": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Growler": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Instinct": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Pipeline": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Romet",
      "flag": null,
      "models": {
        "Rambler": {
          "diameter": 27.2,
          "type": "VTC",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Rose Bikes",
      "flag": null,
      "models": {
        "Root Miller": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Rotwild",
      "flag": null,
      "models": {
        "R.E750": {
          "diameter": 34.9,
          "type": "VTTAE",
          "status": "compatible"
        },
        "R.X375 Pro": {
          "diameter": 34.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Salsa",
      "flag": null,
      "models": {
        "Timberjack": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Santa Cruz",
      "flag": null,
      "models": {
        "5010": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Bronson": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Chameleon": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Hightower": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Megatower": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Nomad": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Tallboy": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Santos Bikes",
      "flag": null,
      "models": {
        "Travelmaster": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Schindelhauer Bikes",
      "flag": null,
      "models": {
        "Hektor": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Ludwig X": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Scott",
      "flag": null,
      "models": {
        "Ransom": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Scale": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible",
          "note": "Clamp 34.9mm. Tube selle 31.6mm confirmé (shim possible)."
        },
        "Spark": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Strike eRIDE": {
          "diameter": 31.6,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Sub Cross": {
          "diameter": 31.6,
          "type": "VTC",
          "status": "compatible"
        },
        "Sub Sport": {
          "diameter": 27.2,
          "type": "Fitness",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Shiftbikes",
      "flag": null,
      "models": {
        "Shift": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Solex",
      "flag": "attention_modele",
      "models": {
        "E-Solex": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "check",
          "note": "Solex moderne utilise des configurations non-standard. Vérifier le modèle."
        }
      }
    },
    {
      "name": "Sparta",
      "flag": null,
      "models": {
        "M8Te": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "R10Te": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Specialized",
      "flag": null,
      "models": {
        "Enduro": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Epic": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Epic EVO": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Kenevo": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Levo": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Sirrus": {
          "diameter": 27.2,
          "type": "Fitness",
          "status": "compatible"
        },
        "Stumpjumper": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Turbo Como": {
          "diameter": 30.9,
          "type": "Ville E",
          "status": "compatible"
        },
        "Turbo Vado": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Stanton Bikes",
      "flag": null,
      "models": {
        "Sherpa": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Slackline": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Stevens Bikes",
      "flag": null,
      "models": {
        "Tonga": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Stöckli Bikes",
      "flag": null,
      "models": {
        "Luxe": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Stromer",
      "flag": null,
      "models": {
        "ST1": {
          "diameter": 31.6,
          "type": "Ville E",
          "status": "compatible"
        },
        "ST2": {
          "diameter": 31.6,
          "type": "Ville E",
          "status": "compatible"
        },
        "ST3": {
          "diameter": 31.6,
          "type": "Ville E",
          "status": "compatible"
        },
        "ST5": {
          "diameter": 31.6,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Sunn",
      "flag": null,
      "models": {
        "Kern": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Pika": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Radical": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Superior Bikes",
      "flag": null,
      "models": {
        "SR XCC 29": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "SR XF 27": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Tecnobike",
      "flag": null,
      "models": {
        "Modèle standard": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Temple Cycles",
      "flag": null,
      "models": {
        "Cycles One": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Tenways",
      "flag": null,
      "models": {
        "CGO600": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "CGO800S": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Tern",
      "flag": null,
      "models": {
        "GSD S10": {
          "diameter": 27.2,
          "type": "Cargo E",
          "status": "compatible"
        },
        "HSD S11": {
          "diameter": 27.2,
          "type": "Cargo E",
          "status": "compatible"
        },
        "Verge X11": {
          "diameter": 27.2,
          "type": "Pliant",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Thömus",
      "flag": null,
      "models": {
        "Lightrider E": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Tiny Rock",
      "flag": null,
      "models": {
        "Modèle standard": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Transition",
      "flag": null,
      "models": {
        "Patrol": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Scout": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Sentinel": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Spire": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Trek",
      "flag": null,
      "models": {
        "FX 3": {
          "diameter": 27.2,
          "type": "Fitness",
          "status": "compatible"
        },
        "FX Sport": {
          "diameter": 27.2,
          "type": "Fitness",
          "status": "compatible"
        },
        "Fuel EX": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Marlin": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Powerfly": {
          "diameter": 31.6,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Procaliber": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Rail": {
          "diameter": 31.6,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Slash": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Supercaliber": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Top Fuel": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        },
        "Verve+": {
          "diameter": 31.6,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Tritao Bikes",
      "flag": null,
      "models": {
        "Modèle standard": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Union Bikes",
      "flag": null,
      "models": {
        "Avalon": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Urban Arrow",
      "flag": "attention_modele",
      "models": {
        "Cargo L": {
          "diameter": 31.6,
          "type": "Cargo E",
          "status": "check",
          "note": "Urban Arrow autorise uniquement des tiges de selle approuvées par la marque (angle de selle spécifique). Vérifier la compatibilité auprès d'un revendeur Urban Arrow."
        },
        "Family": {
          "diameter": 31.6,
          "type": "Cargo E",
          "status": "check",
          "note": "Urban Arrow autorise uniquement des tiges de selle approuvées par la marque (angle de selle spécifique). Vérifier la compatibilité auprès d'un revendeur Urban Arrow."
        },
        "Family Next": {
          "diameter": 31.6,
          "type": "Cargo E",
          "status": "check",
          "note": "Urban Arrow autorise uniquement des tiges de selle approuvées par la marque (angle de selle spécifique). Vérifier la compatibilité auprès d'un revendeur Urban Arrow."
        },
        "Shorty": {
          "diameter": 31.6,
          "type": "Cargo E",
          "status": "check",
          "note": "Urban Arrow autorise uniquement des tiges de selle approuvées par la marque (angle de selle spécifique). Vérifier la compatibilité auprès d'un revendeur Urban Arrow."
        }
      }
    },
    {
      "name": "Urtopia",
      "flag": null,
      "models": {
        "Carbon 1S": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Fusion": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Van Raam",
      "flag": null,
      "models": {
        "Easy Rider": {
          "diameter": 27.2,
          "type": "Tricycle E",
          "status": "compatible"
        },
        "Fun2Go": {
          "diameter": 27.2,
          "type": "Tricycle E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "VanDijck",
      "flag": null,
      "models": {
        "Modèle standard": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "VanMoof",
      "flag": "attention_modele",
      "models": {
        "A5": {
          "diameter": 34,
          "type": "Ville E",
          "status": "check",
          "note": "VanMoof utilise une tige de selle propriétaire de 34mm. La tige Selle Jallot doit être vérifiée pour compatibilité avec ce diamètre spécifique."
        },
        "S5": {
          "diameter": 34,
          "type": "Ville E",
          "status": "check",
          "note": "VanMoof utilise une tige de selle propriétaire de 34mm. La tige Selle Jallot doit être vérifiée pour compatibilité avec ce diamètre spécifique."
        }
      }
    },
    {
      "name": "Vefaa",
      "flag": null,
      "models": {
        "Modèle standard": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Velo de Ville",
      "flag": null,
      "models": {
        "AEB 800": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "CEB 800": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Veloretti",
      "flag": null,
      "models": {
        "Ace": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Cargo Two": {
          "diameter": 27.2,
          "type": "Cargo E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Victoria Bikes",
      "flag": null,
      "models": {
        "eAdventure": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        },
        "eTrekking": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Vitus",
      "flag": null,
      "models": {
        "Mythique": {
          "diameter": 31.6,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "VSF Fahrradmanufaktur",
      "flag": null,
      "models": {
        "S-400": {
          "diameter": 27.2,
          "type": "Ville",
          "status": "compatible"
        },
        "TX-400": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Wayscral",
      "flag": null,
      "models": {
        "Evoway": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Whyte Bikes",
      "flag": null,
      "models": {
        "G-180": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "S-150": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "T-130": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Winora",
      "flag": null,
      "models": {
        "Sinus": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        },
        "Yakun": {
          "diameter": 27.2,
          "type": "VTC E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Woom",
      "flag": null,
      "models": {
        "Woom 6": {
          "diameter": 27.2,
          "type": "Enfant",
          "status": "compatible"
        },
        "Woom UP 6": {
          "diameter": 27.2,
          "type": "Enfant E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Yeti",
      "flag": null,
      "models": {
        "SB115": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "SB130": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "SB150": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "SB160": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "SB165": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Ymagine Bikes",
      "flag": null,
      "models": {
        "Modèle standard": {
          "diameter": 27.2,
          "type": "Ville E",
          "status": "compatible"
        }
      }
    },
    {
      "name": "YT Industries",
      "flag": null,
      "models": {
        "Capra": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Decoy": {
          "diameter": 30.9,
          "type": "VTTAE",
          "status": "compatible"
        },
        "Izzo": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        },
        "Jeffsy": {
          "diameter": 30.9,
          "type": "VTT",
          "status": "compatible"
        }
      }
    },
    {
      "name": "Yuba",
      "flag": null,
      "models": {
        "Boda Boda": {
          "diameter": 27.2,
          "type": "Cargo",
          "status": "compatible"
        },
        "Kombi E": {
          "diameter": 34,
          "type": "Cargo E",
          "status": "compatible"
        },
        "Mundo": {
          "diameter": 34,
          "type": "Cargo",
          "status": "compatible"
        }
      }
    }
  ],
  "incompatibleBrands": [
    {
      "name": "Brompton",
      "reason": "La tige de selle Selle Jallot est trop courte pour un Brompton, qui nécessite une tige extra-longue spécifique.",
      "scope": "all"
    },
    {
      "name": "Crivit (Lidl)",
      "reason": "Batterie intégrée dans la tige de selle sur les modèles e-bike.",
      "scope": [
        "Classic E-bike",
        "URBAN E-BIKE X.2",
        "URBAN E-BIKE Y.2",
        "URBAN E-BIKE X.1",
        "URBAN E-BIKE Y.1"
      ]
    },
    {
      "name": "Eovolt",
      "reason": "Batterie intégrée dans la tige de selle — la tige ne peut pas être remplacée.",
      "scope": "all"
    },
    {
      "name": "UTO",
      "reason": "Batterie intégrée dans la tige de selle — la tige ne peut pas être remplacée.",
      "scope": "all"
    },
    {
      "name": "Voltaire",
      "reason": "Batterie intégrée dans la tige de selle — la tige ne peut pas être remplacée.",
      "scope": "all"
    }
  ]
};

export default database;
